# based on https://github.com/cminers/helm-litecoin/blob/master/values.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litecoin
  labels:
    app.kubernetes.io/name: litecoin
    app.kubernetes.io/instance: cluster-1
    app.kubernetes.io/managed-by: not-helm
spec:
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  serviceName: litecoin
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: litecoin
      app.kubernetes.io/instance: cluster-1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: litecoin
        app.kubernetes.io/instance: cluster-1
    spec:
      containers:
        - name: litecoin
          image: "somerepo/litecoin:0.18.1"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data
              mountPath: "/home/litecoin/.litecoin"
          ports:
            - containerPort: 9332
              protocol: TCP
              name: rpc
            - containerPort: 9338
              protocol: TCP
              name: p2p
            - containerPort: 19333
              protocol: TCP
              name: testnet
          # QoS Guaranteed
          # I don't know if those resources are enough
          resources:
            requests:
              memory: 3Gi
              cpu: 2
            limits:
              memory: 3Gi
              cpu: 2